name: oid4vc-haip-sd-jwt-vc document push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    compile-oid4vc-haip-sd-jwt-vc:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Run the build process with Docker
            run: |     
                docker run \
                -v /${{ github.workspace }}:/data danielfett/markdown2rfc \
                oid4vc-haip-sd-jwt-vc-1_0.md
          - name: rename
            run: |
                mv ./oid4vc-haip-sd-jwt-vc*.html ./oid4vc-haip-sd-jwt-vc-wg-draft.html
          - uses: actions/upload-artifact@v3
            with:
                # Artifact name
                name: output # optional
                # Destination path
                path: ./oid4vc-haip-sd-jwt-vc*.html # optional
    
    publish-to-pages:
      name: Publish to GitHub Pages
      if: github.ref == 'refs/heads/main'
      needs: compile-oid4vc-haip-sd-jwt-vc
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: output
        - name: Upload pages artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: .
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
